name: sync-latest-word
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  sync-words:
    runs-on: ubuntu-latest
    name: sync the latest word from NYT
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
     - uses: actions/cache@v2
       with:
         path: |
           ~/.cargo/registry
           ~/.cargo/git
           target
         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: load-words
        run: cd eb-words && cargo run
      - name: push-code
        run: |
          git add .
          git -c "user.name=GitHub Action (wordlist update)" -c "user.email=wordlist-update@github.com" \
                 commit -m "Update wordlist"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin "$(git rev-parse --abbrev-ref HEAD)"