name: sync-latest-word
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  sync-words:
    runs-on: ubuntu-latest
    name: Push generated code to a branch
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: load-words
        run: cd eb-words && cargo run
      - name: push-code
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin "$(git rev-parse --abbrev-ref HEAD)"